version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: user_management_db
    environment:
      POSTGRES_DB: user_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

  # Backend API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: user_management_server
    environment:
      - NODE_ENV=production
      - PORT=5000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=user_management_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  # Frontend React App
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: user_management_client
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
