[build]
  publish = "client/build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 3000
  publish = "build" 